install.packages("RNeo4j")
install.packages("tictoc")
install.packages("sp")
install.packages("rgeos")
install.packages("httr")
install.packages("jsonlite")
install.packages("igraph")
install.packages("RPostgreSQL")
install.packages("RMySQL")
install.packages("geometry")
install.packages("configc")
install.packages("yaml")
install.packages("itertools")
install.packages("kernlab")
install.packages("gdata")

